name: Ecommercev2 CI

on:
  push:
    branches: [ main ]

jobs:
    builds:
        runs-on: ubuntu-latest
        
        steps:
     
    Step 1:   
        - name: chckout code
        uses: actions/checkout@v3
    
    Step2:
        - name: Setup Node.js 
        uses: actions/setup-node@v3
        with: node-version: '18'
       
    Step 3:
        - name: Install dependencies
        run: npm install

test:
    runs-on: ubuntu-latest
   
    steps:
   
    Step 1:       
    - name: chckout code
      uses: actions/checkout@v3
    
      Step 2:
    - name: Setup Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18'
       
    Step 3:
    - name: Install dependencies
      run: npm install
    
    Step 4:
    - name: Run tests
      run: npm test -- -- watchAll=false

   
